syntax = "proto3";

package users;

option go_package = "finance_manager/proto/users;proto";

import "google/api/annotations.proto";
import "buf/validate/validate.proto";

service UserService {
    rpc SignUp(SignUpRequest) returns (UserResponse) {
        option (google.api.http) = {
            post: "/v1/users/signup"
            body: "*"
        };
    }
    rpc SignIn(SignInRequest) returns (SignInResponse) {
        option (google.api.http) = {
            post: "/v1/users/signin"
            body: "*"
        };
    }
    rpc Logout(LogoutRequest) returns (LogoutResponse) {
        option (google.api.http) = {
            post: "/v1/users/logout"
            body: "*"
        };
    }
    rpc GetUser(GetUserRequest) returns (UserResponse) {
        option (google.api.http) = {
            get: "/v1/users/{user_id}"
        };
    }
    rpc GetAllUsers(EmptyRequest) returns (stream UserIdResponse) {
        option (google.api.http) = {
            get: "/v1/users"
        };
    }
    rpc UpdateUser(UpdateUserRequest) returns (UpdateUserResponse) {
        option (google.api.http) = {
            patch: "/v1/users/{user_id}"
            body: "*"
        };
    }
    rpc DeleteUser(DeleteUserRequest) returns (DeleteUserResponse) {
        option (google.api.http) = {
            delete: "/v1/users/{user_id}"
        };
    }
    
    rpc AddUserAccount(UserAccountRequest) returns (UserAccountResponse) {
        option (google.api.http) = {
            post: "/v1/users/{user_id}/accounts/{id_number}"
            body: "*"
        };
    }
    rpc GetUserAccounts(GetUserAccountsRequest) returns (GetUserAccountsResponse) {
        option (google.api.http) = {
            get: "/v1/users/{user_id}/accounts"
        };
    }
    rpc DeleteUserAccount(UserAccountRequest) returns (UserAccountResponse) {
        option (google.api.http) = {
            delete: "/v1/users/{user_id}/accounts/{id_number}"
        };
    }

    rpc UpdateUserAccountBalance(UserAccountRequest) returns (UserAccountResponse) {}
}

message User {
    int64 id = 1;
    string username = 2;
    string email = 3;
    string password = 4;
    int64 created_at = 5;
    int64 updated_at = 6;
}

message UserAccount {
    string id_number = 1;
    double balance = 2;
}

message SignUpRequest {
    string username = 1 [(buf.validate.field).string.min_len = 1];
    string email = 2 [(buf.validate.field).cel = {
        id: "valid_email"
        message: "email must be a valid email"
        expression: "this.isEmail()"
    }];
    string password = 4 [(buf.validate.field) = {
        cel: [
            {
                id: "password_length",
                message: "password must be between 12 and 20 characters",
                expression: "size(this) >= 12 && size(this) <= 20"
            },
            {
                id: "password_complexity",
                message: "password must contain at least one uppercase letter, one lowercase letter, one number, and one special character",
                expression: "this.matches('[A-Z]') && this.matches('[a-z]') && this.matches('[0-9]') && this.matches('[!@#$%^&*_+-=]')"
            }
        ]
    }];
}

message EmptyRequest {}

message UserIdResponse {
    int64 user_id = 1;
}

message GetUserRequest {
    int64 user_id = 1 [(buf.validate.field).int64.gt = -1];
}

message UserResponse {
    User user = 1;
    repeated string account_numbers = 2;
}

message UpdateUserRequest {
    int64 user_id = 1;
    string username = 2 [(buf.validate.field).string.min_len = 1];
    string email = 3 [(buf.validate.field).cel = {
        id: "valid_email"
        message: "email must be a valid email"
        expression: "this.isEmail()"
    }];
    string password = 4 [(buf.validate.field) = {
        cel: [
            {
            id: "password_length",
            message: "password must be between 12 and 20 characters",
            expression: "size(this) >= 12 && size(this) <= 20"
            },
            {
                id: "password_complexity",
                message: "password must contain at least one uppercase letter, one lowercase letter, one number, and one special character",
                expression: "this.matches('[A-Z]') && this.matches('[a-z]') && this.matches('[0-9]') && this.matches('[!@#$%^&*_+-=]')"
            }
        ]
    }];
}

message UpdateUserResponse {
    bool success = 1;
}

message DeleteUserRequest {
    int64 user_id = 1 [(buf.validate.field).int64.gt = -1];
}

message DeleteUserResponse {
    bool success = 1;
}

message UserAccountRequest {
    int64 user_id = 1 [(buf.validate.field).int64.gt = -1];
    string id_number = 2;
}

message UserAccountResponse {
    bool success = 1;
    double balance = 2;
}

message GetUserAccountsRequest {
    int64 user_id = 1 [(buf.validate.field).int64.gt = -1];
}

message GetUserAccountsResponse {
    repeated UserAccount accounts = 1;
}

message SignInRequest {
    string email = 1 [(buf.validate.field).cel = {
        id: "valid_email"
        message: "email must be a valid email"
        expression: "this.isEmail()"
    }];
    string password = 2;
}

message SignInResponse {
    int64 user_id = 1;
    string token = 2;
}

message LogoutRequest {
    int64 user_id = 1 [(buf.validate.field).int64.gt = -1];
    string token = 2 [(buf.validate.field).string.min_len = 1];
}

message LogoutResponse {
    bool success = 1;
}