networks:
  finance-manager-network:
    driver: bridge

services:
  pg-0:
    image: bitnami/postgresql-repmgr:17.4.0
    container_name: pg-0
    ports:
      - 15432:5432
    volumes:
      - pg_0_data:/bitnami/postgresql
      - ./docker-init.sh:/docker-entrypoint-initdb.d/docker-init.sh
      - ./bank_system/postgres/bank_system.sql:/docker-entrypoint-initdb.d/bank_system.sql
      - ./users/postgres/fm_user.sql:/docker-entrypoint-initdb.d/fm_user.sql
      - ./records/postgres/fm_record.sql:/docker-entrypoint-initdb.d/fm_record.sql
      - ./records_bank/postgres/fm_record_bank.sql:/docker-entrypoint-initdb.d/fm_record_bank.sql
    environment:
      - POSTGRESQL_POSTGRES_PASSWORD=${POSTGRESQL_POSTGRES_PASSWORD}
      - POSTGRESQL_USERNAME=${POSTGRESQL_USERNAME}
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
      - POSTGRESQL_DATABASE=${POSTGRESQL_DATABASE}
      - REPMGR_PASSWORD=${REPMGR_PASSWORD}
      - REPMGR_PRIMARY_HOST=pg-0
      - REPMGR_PARTNER_NODES=pg-0,pg-1
      - REPMGR_NODE_NAME=pg-0
      - REPMGR_NODE_NETWORK_NAME=pg-0
    networks:
      - finance-manager-network
      
  pg-1:
    image: bitnami/postgresql-repmgr:17.4.0
    container_name: pg-1
    ports:
      - 25432:5432
    volumes:
      - pg_1_data:/bitnami/postgresql
    environment:
      - POSTGRESQL_POSTGRES_PASSWORD=${POSTGRESQL_POSTGRES_PASSWORD}
      - POSTGRESQL_USERNAME=${POSTGRESQL_USERNAME}
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
      - POSTGRESQL_DATABASE=${POSTGRESQL_DATABASE}
      - REPMGR_PASSWORD=${REPMGR_PASSWORD}
      - REPMGR_PRIMARY_HOST=pg-0
      - REPMGR_PARTNER_NODES=pg-0,pg-1
      - REPMGR_NODE_NAME=pg-1
      - REPMGR_NODE_NETWORK_NAME=pg-1
    networks:
      - finance-manager-network

  pgpool:
    image: bitnami/pgpool:4.5.5
    container_name: pgpool
    ports:
      - 5432:5432
    environment:
      - PGPOOL_BACKEND_NODES=0:pg-0:5432,1:pg-1:5432
      - PGPOOL_SR_CHECK_USER=${PGPOOL_SR_CHECK_USER}
      - PGPOOL_SR_CHECK_PASSWORD=${PGPOOL_SR_CHECK_PASSWORD}
      - PGPOOL_ENABLE_LDAP=no
      - PGPOOL_POSTGRES_USERNAME=${PGPOOL_POSTGRES_USERNAME}
      - PGPOOL_POSTGRES_PASSWORD=${PGPOOL_POSTGRES_PASSWORD}
      - PGPOOL_ADMIN_USERNAME=${PGPOOL_ADMIN_USERNAME}
      - PGPOOL_ADMIN_PASSWORD=${PGPOOL_ADMIN_PASSWORD}
    healthcheck:
      test: ["CMD", "/opt/bitnami/scripts/pgpool/healthcheck.sh"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - finance-manager-network

  kafka:
    image: 'bitnami/kafka:latest'
    container_name: kafka
    ports:
      - '9094:9094'
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    networks:
      - finance-manager-network

  redis:
    image: redis:8.0-M04-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - finance-manager-network
  
  bank_system:
    build:
      context: ./bank_system
      dockerfile: Dockerfile
    container_name: bank_system
    ports:
      - 8855:8855
    networks:
      - finance-manager-network
    depends_on:
      - pg-0
      - pg-1

volumes:
  pg_0_data:
  pg_1_data:
  redis_data: