// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: fm_record_bank_query.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBankRecordsBulk = `-- name: CreateBankRecordsBulk :many

INSERT INTO "FM_Record_Bank" (
    user_id, 
    account_number, 
    amount, 
    record_type, 
    transaction_id, 
    transaction_date, 
    detail
) VALUES (
    $1::bigint,                -- single user_id
    $2::text,                  -- single account_number
    UNNEST($3::numeric[]),     -- amount array
    UNNEST($4::text[]),        -- record_type array
    UNNEST($5::bigint[]),      -- transaction_id array
    UNNEST($6::TIMESTAMPTZ[]), -- transaction_date array
    UNNEST($7::text[])         -- detail array
)
RETURNING id, user_id, account_number, amount, transaction_id, transaction_date, record_type, detail, created_at
`

type CreateBankRecordsBulkParams struct {
	Column1 int64                `json:"column_1"`
	Column2 string               `json:"column_2"`
	Column3 []float64            `json:"column_3"`
	Column4 []string             `json:"column_4"`
	Column5 []int64              `json:"column_5"`
	Column6 []pgtype.Timestamptz `json:"column_6"`
	Column7 []string             `json:"column_7"`
}

// Table: FM_Record_Bank
func (q *Queries) CreateBankRecordsBulk(ctx context.Context, arg CreateBankRecordsBulkParams) ([]FMRecordBank, error) {
	rows, err := q.db.Query(ctx, createBankRecordsBulk,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Column7,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FMRecordBank
	for rows.Next() {
		var i FMRecordBank
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AccountNumber,
			&i.Amount,
			&i.TransactionID,
			&i.TransactionDate,
			&i.RecordType,
			&i.Detail,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBankRecord = `-- name: GetBankRecord :one
SELECT id, user_id, account_number, amount, transaction_id, transaction_date, record_type, detail, created_at FROM "FM_Record_Bank" WHERE id = $1
`

func (q *Queries) GetBankRecord(ctx context.Context, id int64) (FMRecordBank, error) {
	row := q.db.QueryRow(ctx, getBankRecord, id)
	var i FMRecordBank
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountNumber,
		&i.Amount,
		&i.TransactionID,
		&i.TransactionDate,
		&i.RecordType,
		&i.Detail,
		&i.CreatedAt,
	)
	return i, err
}

const getExistingBankRecords = `-- name: GetExistingBankRecords :many
SELECT transaction_id FROM "FM_Record_Bank" WHERE transaction_id = ANY($1::bigint[])
`

func (q *Queries) GetExistingBankRecords(ctx context.Context, dollar_1 []int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, getExistingBankRecords, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var transaction_id int64
		if err := rows.Scan(&transaction_id); err != nil {
			return nil, err
		}
		items = append(items, transaction_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserBankRecords = `-- name: GetUserBankRecords :many
SELECT id, user_id, account_number, amount, transaction_id, transaction_date, record_type, detail, created_at FROM "FM_Record_Bank" WHERE user_id = $1 AND account_number = $2
`

type GetUserBankRecordsParams struct {
	UserID        int64  `json:"user_id"`
	AccountNumber string `json:"account_number"`
}

func (q *Queries) GetUserBankRecords(ctx context.Context, arg GetUserBankRecordsParams) ([]FMRecordBank, error) {
	rows, err := q.db.Query(ctx, getUserBankRecords, arg.UserID, arg.AccountNumber)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FMRecordBank
	for rows.Next() {
		var i FMRecordBank
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AccountNumber,
			&i.Amount,
			&i.TransactionID,
			&i.TransactionDate,
			&i.RecordType,
			&i.Detail,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserBankRecordsByType = `-- name: GetUserBankRecordsByType :many
SELECT id, user_id, account_number, amount, transaction_id, transaction_date, record_type, detail, created_at FROM "FM_Record_Bank"
WHERE user_id = $1 AND account_number = $2 AND record_type = $3
`

type GetUserBankRecordsByTypeParams struct {
	UserID        int64  `json:"user_id"`
	AccountNumber string `json:"account_number"`
	RecordType    string `json:"record_type"`
}

func (q *Queries) GetUserBankRecordsByType(ctx context.Context, arg GetUserBankRecordsByTypeParams) ([]FMRecordBank, error) {
	rows, err := q.db.Query(ctx, getUserBankRecordsByType, arg.UserID, arg.AccountNumber, arg.RecordType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FMRecordBank
	for rows.Next() {
		var i FMRecordBank
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AccountNumber,
			&i.Amount,
			&i.TransactionID,
			&i.TransactionDate,
			&i.RecordType,
			&i.Detail,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserBankRecordsByTypeFromDate = `-- name: GetUserBankRecordsByTypeFromDate :many
SELECT id, user_id, account_number, amount, transaction_id, transaction_date, record_type, detail, created_at FROM "FM_Record_Bank"
WHERE user_id = $1 AND account_number = $2 AND record_type = $3 AND created_at >= $4
`

type GetUserBankRecordsByTypeFromDateParams struct {
	UserID        int64              `json:"user_id"`
	AccountNumber string             `json:"account_number"`
	RecordType    string             `json:"record_type"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetUserBankRecordsByTypeFromDate(ctx context.Context, arg GetUserBankRecordsByTypeFromDateParams) ([]FMRecordBank, error) {
	rows, err := q.db.Query(ctx, getUserBankRecordsByTypeFromDate,
		arg.UserID,
		arg.AccountNumber,
		arg.RecordType,
		arg.CreatedAt,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FMRecordBank
	for rows.Next() {
		var i FMRecordBank
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AccountNumber,
			&i.Amount,
			&i.TransactionID,
			&i.TransactionDate,
			&i.RecordType,
			&i.Detail,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserBankRecordsByTypeToDate = `-- name: GetUserBankRecordsByTypeToDate :many
SELECT id, user_id, account_number, amount, transaction_id, transaction_date, record_type, detail, created_at FROM "FM_Record_Bank"
WHERE user_id = $1 AND account_number = $2 AND record_type = $3 AND created_at <= $4
`

type GetUserBankRecordsByTypeToDateParams struct {
	UserID        int64              `json:"user_id"`
	AccountNumber string             `json:"account_number"`
	RecordType    string             `json:"record_type"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetUserBankRecordsByTypeToDate(ctx context.Context, arg GetUserBankRecordsByTypeToDateParams) ([]FMRecordBank, error) {
	rows, err := q.db.Query(ctx, getUserBankRecordsByTypeToDate,
		arg.UserID,
		arg.AccountNumber,
		arg.RecordType,
		arg.CreatedAt,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FMRecordBank
	for rows.Next() {
		var i FMRecordBank
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AccountNumber,
			&i.Amount,
			&i.TransactionID,
			&i.TransactionDate,
			&i.RecordType,
			&i.Detail,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserBankRecordsByTypeWithPeriod = `-- name: GetUserBankRecordsByTypeWithPeriod :many
SELECT id, user_id, account_number, amount, transaction_id, transaction_date, record_type, detail, created_at FROM "FM_Record_Bank"
WHERE user_id = $1 AND account_number = $2 AND record_type = $3 AND created_at BETWEEN $4 AND $5
`

type GetUserBankRecordsByTypeWithPeriodParams struct {
	UserID        int64              `json:"user_id"`
	AccountNumber string             `json:"account_number"`
	RecordType    string             `json:"record_type"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	CreatedAt_2   pgtype.Timestamptz `json:"created_at_2"`
}

func (q *Queries) GetUserBankRecordsByTypeWithPeriod(ctx context.Context, arg GetUserBankRecordsByTypeWithPeriodParams) ([]FMRecordBank, error) {
	rows, err := q.db.Query(ctx, getUserBankRecordsByTypeWithPeriod,
		arg.UserID,
		arg.AccountNumber,
		arg.RecordType,
		arg.CreatedAt,
		arg.CreatedAt_2,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FMRecordBank
	for rows.Next() {
		var i FMRecordBank
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AccountNumber,
			&i.Amount,
			&i.TransactionID,
			&i.TransactionDate,
			&i.RecordType,
			&i.Detail,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserBankRecordsFromDate = `-- name: GetUserBankRecordsFromDate :many
SELECT id, user_id, account_number, amount, transaction_id, transaction_date, record_type, detail, created_at FROM "FM_Record_Bank"
WHERE user_id = $1 AND account_number = $2 AND created_at >= $3
`

type GetUserBankRecordsFromDateParams struct {
	UserID        int64              `json:"user_id"`
	AccountNumber string             `json:"account_number"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetUserBankRecordsFromDate(ctx context.Context, arg GetUserBankRecordsFromDateParams) ([]FMRecordBank, error) {
	rows, err := q.db.Query(ctx, getUserBankRecordsFromDate, arg.UserID, arg.AccountNumber, arg.CreatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FMRecordBank
	for rows.Next() {
		var i FMRecordBank
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AccountNumber,
			&i.Amount,
			&i.TransactionID,
			&i.TransactionDate,
			&i.RecordType,
			&i.Detail,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserBankRecordsToDate = `-- name: GetUserBankRecordsToDate :many
SELECT id, user_id, account_number, amount, transaction_id, transaction_date, record_type, detail, created_at FROM "FM_Record_Bank"
WHERE user_id = $1 AND account_number = $2 AND created_at <= $3
`

type GetUserBankRecordsToDateParams struct {
	UserID        int64              `json:"user_id"`
	AccountNumber string             `json:"account_number"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetUserBankRecordsToDate(ctx context.Context, arg GetUserBankRecordsToDateParams) ([]FMRecordBank, error) {
	rows, err := q.db.Query(ctx, getUserBankRecordsToDate, arg.UserID, arg.AccountNumber, arg.CreatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FMRecordBank
	for rows.Next() {
		var i FMRecordBank
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AccountNumber,
			&i.Amount,
			&i.TransactionID,
			&i.TransactionDate,
			&i.RecordType,
			&i.Detail,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserBankRecordsWithPeriod = `-- name: GetUserBankRecordsWithPeriod :many
SELECT id, user_id, account_number, amount, transaction_id, transaction_date, record_type, detail, created_at FROM "FM_Record_Bank"
WHERE user_id = $1 AND account_number = $2 AND created_at BETWEEN $3 AND $4
`

type GetUserBankRecordsWithPeriodParams struct {
	UserID        int64              `json:"user_id"`
	AccountNumber string             `json:"account_number"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	CreatedAt_2   pgtype.Timestamptz `json:"created_at_2"`
}

func (q *Queries) GetUserBankRecordsWithPeriod(ctx context.Context, arg GetUserBankRecordsWithPeriodParams) ([]FMRecordBank, error) {
	rows, err := q.db.Query(ctx, getUserBankRecordsWithPeriod,
		arg.UserID,
		arg.AccountNumber,
		arg.CreatedAt,
		arg.CreatedAt_2,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FMRecordBank
	for rows.Next() {
		var i FMRecordBank
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AccountNumber,
			&i.Amount,
			&i.TransactionID,
			&i.TransactionDate,
			&i.RecordType,
			&i.Detail,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
