// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type FMRecordBank struct {
	ID              int64              `json:"id"`
	UserID          int64              `json:"user_id"`
	AccountNumber   string             `json:"account_number"`
	Amount          float64            `json:"amount"`
	TransactionID   int64              `json:"transaction_id"`
	TransactionDate pgtype.Timestamptz `json:"transaction_date"`
	RecordType      string             `json:"record_type"`
	Detail          string             `json:"detail"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}
