// Code generated by mockery v2.52.3. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	sqlc "users/postgres/sqlc"
)

// UserRepository is an autogenerated mock type for the UserRepository type
type UserRepository struct {
	mock.Mock
}

// CheckUserEmailExists provides a mock function with given fields: email
func (_m *UserRepository) CheckUserEmailExists(email string) (bool, error) {
	ret := _m.Called(email)

	if len(ret) == 0 {
		panic("no return value specified for CheckUserEmailExists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (bool, error)); ok {
		return rf(email)
	}
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(email)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CheckUserExists provides a mock function with given fields: id
func (_m *UserRepository) CheckUserExists(id int64) (bool, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for CheckUserExists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(int64) (bool, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int64) bool); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(int64) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateUser provides a mock function with given fields: username, email, password
func (_m *UserRepository) CreateUser(username string, email string, password string) (sqlc.User, error) {
	ret := _m.Called(username, email, password)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 sqlc.User
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, string) (sqlc.User, error)); ok {
		return rf(username, email, password)
	}
	if rf, ok := ret.Get(0).(func(string, string, string) sqlc.User); ok {
		r0 = rf(username, email, password)
	} else {
		r0 = ret.Get(0).(sqlc.User)
	}

	if rf, ok := ret.Get(1).(func(string, string, string) error); ok {
		r1 = rf(username, email, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteUser provides a mock function with given fields: id
func (_m *UserRepository) DeleteUser(id int64) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int64) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAllUsers provides a mock function with no fields
func (_m *UserRepository) GetAllUsers() ([]sqlc.User, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAllUsers")
	}

	var r0 []sqlc.User
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]sqlc.User, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []sqlc.User); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]sqlc.User)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserByEmail provides a mock function with given fields: email
func (_m *UserRepository) GetUserByEmail(email string) (sqlc.User, error) {
	ret := _m.Called(email)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByEmail")
	}

	var r0 sqlc.User
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (sqlc.User, error)); ok {
		return rf(email)
	}
	if rf, ok := ret.Get(0).(func(string) sqlc.User); ok {
		r0 = rf(email)
	} else {
		r0 = ret.Get(0).(sqlc.User)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserById provides a mock function with given fields: id
func (_m *UserRepository) GetUserById(id int64) (sqlc.User, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetUserById")
	}

	var r0 sqlc.User
	var r1 error
	if rf, ok := ret.Get(0).(func(int64) (sqlc.User, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int64) sqlc.User); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(sqlc.User)
	}

	if rf, ok := ret.Get(1).(func(int64) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateUser provides a mock function with given fields: id, username, email, password
func (_m *UserRepository) UpdateUser(id int64, username string, email string, password string) error {
	ret := _m.Called(id, username, email, password)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int64, string, string, string) error); ok {
		r0 = rf(id, username, email, password)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewUserRepository creates a new instance of UserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserRepository {
	mock := &UserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
