// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: fm_user_query.sql

package sqlc

import (
	"context"
)

const checkUserEmailExists = `-- name: CheckUserEmailExists :one
SELECT EXISTS (
  SELECT 1 FROM "FM_User" WHERE email = $1
) AS email_exists
`

func (q *Queries) CheckUserEmailExists(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRow(ctx, checkUserEmailExists, email)
	var email_exists bool
	err := row.Scan(&email_exists)
	return email_exists, err
}

const checkUserExists = `-- name: CheckUserExists :one
SELECT EXISTS (
  SELECT 1 FROM "FM_User" WHERE id = $1
) AS user_exists
`

func (q *Queries) CheckUserExists(ctx context.Context, id int64) (bool, error) {
	row := q.db.QueryRow(ctx, checkUserExists, id)
	var user_exists bool
	err := row.Scan(&user_exists)
	return user_exists, err
}

const createUser = `-- name: CreateUser :one

INSERT INTO "FM_User" (username, email, password)
VALUES ($1, $2, $3)
RETURNING id, username, email, password, created_at, updated_at
`

type CreateUserParams struct {
	Username string `json:"username"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

// Table: User
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (FMUser, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Username, arg.Email, arg.Password)
	var i FMUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM "FM_User" WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getAllUsers = `-- name: GetAllUsers :many
SELECT id, username, email, password, created_at, updated_at FROM "FM_User" ORDER BY created_at OFFSET $1 LIMIT $2
`

type GetAllUsersParams struct {
	Offset int32 `json:"offset"`
	Limit  int32 `json:"limit"`
}

func (q *Queries) GetAllUsers(ctx context.Context, arg GetAllUsersParams) ([]FMUser, error) {
	rows, err := q.db.Query(ctx, getAllUsers, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FMUser
	for rows.Next() {
		var i FMUser
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.Password,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, username, email, password, created_at, updated_at FROM "FM_User" WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (FMUser, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i FMUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserById = `-- name: GetUserById :one
SELECT id, username, email, password, created_at, updated_at FROM "FM_User" WHERE id = $1
`

func (q *Queries) GetUserById(ctx context.Context, id int64) (FMUser, error) {
	row := q.db.QueryRow(ctx, getUserById, id)
	var i FMUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE "FM_User" SET username = $2, email = $3, password = $4, updated_at = NOW() WHERE id = $1
`

type UpdateUserParams struct {
	ID       int64  `json:"id"`
	Username string `json:"username"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.Exec(ctx, updateUser,
		arg.ID,
		arg.Username,
		arg.Email,
		arg.Password,
	)
	return err
}
