// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: fm_user_query.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addAccount = `-- name: AddAccount :one

INSERT INTO "FM_Account" (user_id, id_number, balance)
VALUES ($1, $2, $3)
RETURNING id, user_id, id_number, balance, created_at, updated_at
`

type AddAccountParams struct {
	UserID   int64   `json:"user_id"`
	IDNumber string  `json:"id_number"`
	Balance  float64 `json:"balance"`
}

// table: FM_Account
func (q *Queries) AddAccount(ctx context.Context, arg AddAccountParams) (FMAccount, error) {
	row := q.db.QueryRow(ctx, addAccount, arg.UserID, arg.IDNumber, arg.Balance)
	var i FMAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.IDNumber,
		&i.Balance,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const checkAccountExists = `-- name: CheckAccountExists :one
SELECT EXISTS (
  SELECT 1 FROM "FM_Account" WHERE user_id = $1 AND id_number = $2
) AS account_exists
`

type CheckAccountExistsParams struct {
	UserID   int64  `json:"user_id"`
	IDNumber string `json:"id_number"`
}

func (q *Queries) CheckAccountExists(ctx context.Context, arg CheckAccountExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkAccountExists, arg.UserID, arg.IDNumber)
	var account_exists bool
	err := row.Scan(&account_exists)
	return account_exists, err
}

const checkUserEmailExists = `-- name: CheckUserEmailExists :one
SELECT EXISTS (
  SELECT 1 FROM "FM_User" WHERE email = $1
) AS email_exists
`

func (q *Queries) CheckUserEmailExists(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRow(ctx, checkUserEmailExists, email)
	var email_exists bool
	err := row.Scan(&email_exists)
	return email_exists, err
}

const checkUserExists = `-- name: CheckUserExists :one
SELECT EXISTS (
  SELECT 1 FROM "FM_User" WHERE id = $1
) AS user_exists
`

func (q *Queries) CheckUserExists(ctx context.Context, id int64) (bool, error) {
	row := q.db.QueryRow(ctx, checkUserExists, id)
	var user_exists bool
	err := row.Scan(&user_exists)
	return user_exists, err
}

const createUser = `-- name: CreateUser :one

INSERT INTO "FM_User" (username, email, password)
VALUES ($1, $2, $3)
RETURNING id, username, email, password, created_at, updated_at
`

type CreateUserParams struct {
	Username string `json:"username"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

// Table: FM_User
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (FMUser, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Username, arg.Email, arg.Password)
	var i FMUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAccount = `-- name: DeleteAccount :exec
DELETE FROM "FM_Account" WHERE id_number = $1
`

func (q *Queries) DeleteAccount(ctx context.Context, idNumber string) error {
	_, err := q.db.Exec(ctx, deleteAccount, idNumber)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM "FM_User" WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getAllUsers = `-- name: GetAllUsers :many
SELECT id FROM "FM_User" ORDER BY created_at
`

func (q *Queries) GetAllUsers(ctx context.Context) ([]int64, error) {
	rows, err := q.db.Query(ctx, getAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserAccounts = `-- name: GetUserAccounts :many
SELECT id, user_id, id_number, balance, created_at, updated_at FROM "FM_Account" WHERE user_id = $1
`

func (q *Queries) GetUserAccounts(ctx context.Context, userID int64) ([]FMAccount, error) {
	rows, err := q.db.Query(ctx, getUserAccounts, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FMAccount
	for rows.Next() {
		var i FMAccount
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.IDNumber,
			&i.Balance,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT 
  u.id, u.username, u.email, u.password, u.created_at, u.updated_at,
  ARRAY_AGG(COALESCE(a.id_number, ''))::TEXT[] AS account_numbers
FROM "FM_User" u
LEFT JOIN "FM_Account" a ON u.id = a.user_id
WHERE u.email = $1
GROUP BY u.id
`

type GetUserByEmailRow struct {
	ID             int64              `json:"id"`
	Username       string             `json:"username"`
	Email          string             `json:"email"`
	Password       string             `json:"password"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	AccountNumbers []string           `json:"account_numbers"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AccountNumbers,
	)
	return i, err
}

const getUserById = `-- name: GetUserById :one
SELECT 
  u.id, u.username, u.email, u.password, u.created_at, u.updated_at,
  ARRAY_AGG(COALESCE(a.id_number, ''))::TEXT[] AS account_numbers
FROM "FM_User" u
LEFT JOIN "FM_Account" a ON u.id = a.user_id
WHERE u.id = $1
GROUP BY u.id
`

type GetUserByIdRow struct {
	ID             int64              `json:"id"`
	Username       string             `json:"username"`
	Email          string             `json:"email"`
	Password       string             `json:"password"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	AccountNumbers []string           `json:"account_numbers"`
}

func (q *Queries) GetUserById(ctx context.Context, id int64) (GetUserByIdRow, error) {
	row := q.db.QueryRow(ctx, getUserById, id)
	var i GetUserByIdRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AccountNumbers,
	)
	return i, err
}

const updateAccountBalance = `-- name: UpdateAccountBalance :exec
UPDATE "FM_Account" SET balance = $2, updated_at = NOW() WHERE id = $1
`

type UpdateAccountBalanceParams struct {
	ID      int64   `json:"id"`
	Balance float64 `json:"balance"`
}

func (q *Queries) UpdateAccountBalance(ctx context.Context, arg UpdateAccountBalanceParams) error {
	_, err := q.db.Exec(ctx, updateAccountBalance, arg.ID, arg.Balance)
	return err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE "FM_User" SET username = $2, email = $3, password = $4, updated_at = NOW() WHERE id = $1
`

type UpdateUserParams struct {
	ID       int64  `json:"id"`
	Username string `json:"username"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.Exec(ctx, updateUser,
		arg.ID,
		arg.Username,
		arg.Email,
		arg.Password,
	)
	return err
}
