// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: bank_system_query.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkAccountIDNumberExists = `-- name: CheckAccountIDNumberExists :one
SELECT EXISTS (
  SELECT 1 FROM "BK_Account" WHERE id_number = $1
) AS id_number_exists
`

func (q *Queries) CheckAccountIDNumberExists(ctx context.Context, idNumber string) (bool, error) {
	row := q.db.QueryRow(ctx, checkAccountIDNumberExists, idNumber)
	var id_number_exists bool
	err := row.Scan(&id_number_exists)
	return id_number_exists, err
}

const checkUserEmailExists = `-- name: CheckUserEmailExists :one
SELECT EXISTS (
  SELECT 1 FROM "BK_User" WHERE email = $1
) AS email_exists
`

func (q *Queries) CheckUserEmailExists(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRow(ctx, checkUserEmailExists, email)
	var email_exists bool
	err := row.Scan(&email_exists)
	return email_exists, err
}

const createAccount = `-- name: CreateAccount :one
INSERT INTO "BK_Account" (user_id, id_number)
VALUES ($1, generate_account_number())
RETURNING id, user_id, id_number, balance, created_at, updated_at
`

func (q *Queries) CreateAccount(ctx context.Context, userID int64) (BKAccount, error) {
	row := q.db.QueryRow(ctx, createAccount, userID)
	var i BKAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.IDNumber,
		&i.Balance,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO "BK_Transaction" (
    account_id, 
    amount, 
    balance_after, 
    tx_type, 
    detail
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, account_id, amount, balance_after, tx_type, detail, created_at
`

type CreateTransactionParams struct {
	AccountID    int64   `json:"account_id"`
	Amount       float64 `json:"amount"`
	BalanceAfter float64 `json:"balance_after"`
	TxType       string  `json:"tx_type"`
	Detail       string  `json:"detail"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (BKTransaction, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.AccountID,
		arg.Amount,
		arg.BalanceAfter,
		arg.TxType,
		arg.Detail,
	)
	var i BKTransaction
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Amount,
		&i.BalanceAfter,
		&i.TxType,
		&i.Detail,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO "BK_User" (username, email, password)
VALUES ($1, $2, $3)
RETURNING id, username, email, password, created_at, updated_at
`

type CreateUserParams struct {
	Username string `json:"username"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (BKUser, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Username, arg.Email, arg.Password)
	var i BKUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const depositToAccount = `-- name: DepositToAccount :one
SELECT new_balance::NUMERIC, transaction_id::BIGINT FROM deposit_to_account($1, $2, $3)
`

type DepositToAccountParams struct {
	AccountID int64   `json:"account_id"`
	Amount    float64 `json:"amount"`
	TxDetail  string  `json:"tx_detail"`
}

type DepositToAccountRow struct {
	NewBalance    float64 `json:"new_balance"`
	TransactionID int64   `json:"transaction_id"`
}

// $1: account ID
// $2: amount to deposit
// $3: Transaction detail
func (q *Queries) DepositToAccount(ctx context.Context, arg DepositToAccountParams) (DepositToAccountRow, error) {
	row := q.db.QueryRow(ctx, depositToAccount, arg.AccountID, arg.Amount, arg.TxDetail)
	var i DepositToAccountRow
	err := row.Scan(&i.NewBalance, &i.TransactionID)
	return i, err
}

const getAccountBalance = `-- name: GetAccountBalance :one
SELECT balance
FROM "BK_Account"
WHERE id = $1
`

func (q *Queries) GetAccountBalance(ctx context.Context, id int64) (float64, error) {
	row := q.db.QueryRow(ctx, getAccountBalance, id)
	var balance float64
	err := row.Scan(&balance)
	return balance, err
}

const getAccountByIDNumber = `-- name: GetAccountByIDNumber :one
SELECT id, user_id, balance, created_at, updated_at
FROM "BK_Account"
WHERE id_number = $1
`

type GetAccountByIDNumberRow struct {
	ID        int64              `json:"id"`
	UserID    int64              `json:"user_id"`
	Balance   float64            `json:"balance"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetAccountByIDNumber(ctx context.Context, idNumber string) (GetAccountByIDNumberRow, error) {
	row := q.db.QueryRow(ctx, getAccountByIDNumber, idNumber)
	var i GetAccountByIDNumberRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Balance,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountTransactionsByIDNumber = `-- name: GetAccountTransactionsByIDNumber :many
SELECT t.id, t.amount, t.tx_type, t.detail, t.created_at
FROM "BK_Transaction" t
JOIN "BK_Account" a ON t.account_id = a.id
WHERE a.id_number = $1
ORDER BY t.created_at DESC
`

type GetAccountTransactionsByIDNumberRow struct {
	ID        int64              `json:"id"`
	Amount    float64            `json:"amount"`
	TxType    string             `json:"tx_type"`
	Detail    string             `json:"detail"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetAccountTransactionsByIDNumber(ctx context.Context, idNumber string) ([]GetAccountTransactionsByIDNumberRow, error) {
	rows, err := q.db.Query(ctx, getAccountTransactionsByIDNumber, idNumber)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAccountTransactionsByIDNumberRow
	for rows.Next() {
		var i GetAccountTransactionsByIDNumberRow
		if err := rows.Scan(
			&i.ID,
			&i.Amount,
			&i.TxType,
			&i.Detail,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllAccounts = `-- name: GetAllAccounts :many
SELECT id, id_number, user_id
FROM "BK_Account"
`

type GetAllAccountsRow struct {
	ID       int64  `json:"id"`
	IDNumber string `json:"id_number"`
	UserID   int64  `json:"user_id"`
}

func (q *Queries) GetAllAccounts(ctx context.Context) ([]GetAllAccountsRow, error) {
	rows, err := q.db.Query(ctx, getAllAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllAccountsRow
	for rows.Next() {
		var i GetAllAccountsRow
		if err := rows.Scan(&i.ID, &i.IDNumber, &i.UserID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllUsers = `-- name: GetAllUsers :many
SELECT id, username
FROM "BK_User"
`

type GetAllUsersRow struct {
	ID       int64  `json:"id"`
	Username string `json:"username"`
}

func (q *Queries) GetAllUsers(ctx context.Context) ([]GetAllUsersRow, error) {
	rows, err := q.db.Query(ctx, getAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllUsersRow
	for rows.Next() {
		var i GetAllUsersRow
		if err := rows.Scan(&i.ID, &i.Username); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransactionByID = `-- name: GetTransactionByID :one
SELECT id, account_id, amount, balance_after, tx_type, detail, created_at
FROM "BK_Transaction"
WHERE id = $1
`

func (q *Queries) GetTransactionByID(ctx context.Context, id int64) (BKTransaction, error) {
	row := q.db.QueryRow(ctx, getTransactionByID, id)
	var i BKTransaction
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Amount,
		&i.BalanceAfter,
		&i.TxType,
		&i.Detail,
		&i.CreatedAt,
	)
	return i, err
}

const getUserAccounts = `-- name: GetUserAccounts :many
SELECT id, id_number, balance
FROM "BK_Account"
WHERE user_id = $1
`

type GetUserAccountsRow struct {
	ID       int64   `json:"id"`
	IDNumber string  `json:"id_number"`
	Balance  float64 `json:"balance"`
}

func (q *Queries) GetUserAccounts(ctx context.Context, userID int64) ([]GetUserAccountsRow, error) {
	rows, err := q.db.Query(ctx, getUserAccounts, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserAccountsRow
	for rows.Next() {
		var i GetUserAccountsRow
		if err := rows.Scan(&i.ID, &i.IDNumber, &i.Balance); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByID = `-- name: GetUserByID :one
SELECT username, email, created_at, updated_at
FROM "BK_User"
WHERE id = $1
`

type GetUserByIDRow struct {
	Username  string             `json:"username"`
	Email     string             `json:"email"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetUserByID(ctx context.Context, id int64) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.Username,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE "BK_User"
SET username = $2, email = $3, password = $4, updated_at = NOW()
WHERE id = $1
RETURNING id, username, email, password, created_at, updated_at
`

type UpdateUserParams struct {
	ID       int64  `json:"id"`
	Username string `json:"username"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (BKUser, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.Username,
		arg.Email,
		arg.Password,
	)
	var i BKUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const withdrawFromAccount = `-- name: WithdrawFromAccount :one
SELECT new_balance::NUMERIC, transaction_id::BIGINT FROM withdraw_from_account($1, $2, $3)
`

type WithdrawFromAccountParams struct {
	AccountID int64   `json:"account_id"`
	Amount    float64 `json:"amount"`
	TxDetail  string  `json:"tx_detail"`
}

type WithdrawFromAccountRow struct {
	NewBalance    float64 `json:"new_balance"`
	TransactionID int64   `json:"transaction_id"`
}

// Withdraws the specified amount from the account balance.
// $1: account ID
// $2: amount to withdraw
// $3: Transaction detail
func (q *Queries) WithdrawFromAccount(ctx context.Context, arg WithdrawFromAccountParams) (WithdrawFromAccountRow, error) {
	row := q.db.QueryRow(ctx, withdrawFromAccount, arg.AccountID, arg.Amount, arg.TxDetail)
	var i WithdrawFromAccountRow
	err := row.Scan(&i.NewBalance, &i.TransactionID)
	return i, err
}
