// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type BKAccount struct {
	ID        int64              `json:"id"`
	UserID    int64              `json:"user_id"`
	IDNumber  string             `json:"id_number"`
	Balance   float64            `json:"balance"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type BKTransaction struct {
	ID           int64              `json:"id"`
	AccountID    int64              `json:"account_id"`
	Amount       float64            `json:"amount"`
	BalanceAfter float64            `json:"balance_after"`
	TxType       string             `json:"tx_type"`
	Detail       string             `json:"detail"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type BKUser struct {
	ID        int64              `json:"id"`
	Username  string             `json:"username"`
	Email     string             `json:"email"`
	Password  string             `json:"password"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}
