// Code generated by mockery v2.52.3. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	sqlc "records/postgres/sqlc"
)

// RecordRepository is an autogenerated mock type for the RecordRepository type
type RecordRepository struct {
	mock.Mock
}

// CreateRecord provides a mock function with given fields: ctx, userId, amount, transactionDate, recordType, detail
func (_m *RecordRepository) CreateRecord(ctx context.Context, userId int64, amount float32, transactionDate int64, recordType string, detail string) (sqlc.FMRecord, error) {
	ret := _m.Called(ctx, userId, amount, transactionDate, recordType, detail)

	if len(ret) == 0 {
		panic("no return value specified for CreateRecord")
	}

	var r0 sqlc.FMRecord
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, float32, int64, string, string) (sqlc.FMRecord, error)); ok {
		return rf(ctx, userId, amount, transactionDate, recordType, detail)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, float32, int64, string, string) sqlc.FMRecord); ok {
		r0 = rf(ctx, userId, amount, transactionDate, recordType, detail)
	} else {
		r0 = ret.Get(0).(sqlc.FMRecord)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, float32, int64, string, string) error); ok {
		r1 = rf(ctx, userId, amount, transactionDate, recordType, detail)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteRecord provides a mock function with given fields: ctx, id
func (_m *RecordRepository) DeleteRecord(ctx context.Context, id int64) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteRecord")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetRecord provides a mock function with given fields: ctx, id
func (_m *RecordRepository) GetRecord(ctx context.Context, id int64) (*sqlc.FMRecord, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetRecord")
	}

	var r0 *sqlc.FMRecord
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*sqlc.FMRecord, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *sqlc.FMRecord); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sqlc.FMRecord)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserRecords provides a mock function with given fields: ctx, userId
func (_m *RecordRepository) GetUserRecords(ctx context.Context, userId int64) ([]sqlc.FMRecord, error) {
	ret := _m.Called(ctx, userId)

	if len(ret) == 0 {
		panic("no return value specified for GetUserRecords")
	}

	var r0 []sqlc.FMRecord
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) ([]sqlc.FMRecord, error)); ok {
		return rf(ctx, userId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) []sqlc.FMRecord); ok {
		r0 = rf(ctx, userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]sqlc.FMRecord)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserRecordsByType provides a mock function with given fields: ctx, userId, recordType
func (_m *RecordRepository) GetUserRecordsByType(ctx context.Context, userId int64, recordType string) ([]sqlc.FMRecord, error) {
	ret := _m.Called(ctx, userId, recordType)

	if len(ret) == 0 {
		panic("no return value specified for GetUserRecordsByType")
	}

	var r0 []sqlc.FMRecord
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string) ([]sqlc.FMRecord, error)); ok {
		return rf(ctx, userId, recordType)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, string) []sqlc.FMRecord); ok {
		r0 = rf(ctx, userId, recordType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]sqlc.FMRecord)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, string) error); ok {
		r1 = rf(ctx, userId, recordType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserRecordsByTypeFromDate provides a mock function with given fields: ctx, userId, recordType, date
func (_m *RecordRepository) GetUserRecordsByTypeFromDate(ctx context.Context, userId int64, recordType string, date int64) ([]sqlc.FMRecord, error) {
	ret := _m.Called(ctx, userId, recordType, date)

	if len(ret) == 0 {
		panic("no return value specified for GetUserRecordsByTypeFromDate")
	}

	var r0 []sqlc.FMRecord
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string, int64) ([]sqlc.FMRecord, error)); ok {
		return rf(ctx, userId, recordType, date)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, string, int64) []sqlc.FMRecord); ok {
		r0 = rf(ctx, userId, recordType, date)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]sqlc.FMRecord)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, string, int64) error); ok {
		r1 = rf(ctx, userId, recordType, date)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserRecordsByTypeToDate provides a mock function with given fields: ctx, userId, recordType, date
func (_m *RecordRepository) GetUserRecordsByTypeToDate(ctx context.Context, userId int64, recordType string, date int64) ([]sqlc.FMRecord, error) {
	ret := _m.Called(ctx, userId, recordType, date)

	if len(ret) == 0 {
		panic("no return value specified for GetUserRecordsByTypeToDate")
	}

	var r0 []sqlc.FMRecord
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string, int64) ([]sqlc.FMRecord, error)); ok {
		return rf(ctx, userId, recordType, date)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, string, int64) []sqlc.FMRecord); ok {
		r0 = rf(ctx, userId, recordType, date)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]sqlc.FMRecord)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, string, int64) error); ok {
		r1 = rf(ctx, userId, recordType, date)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserRecordsByTypeWithPeriod provides a mock function with given fields: ctx, userId, recordType, startTime, endTime
func (_m *RecordRepository) GetUserRecordsByTypeWithPeriod(ctx context.Context, userId int64, recordType string, startTime int64, endTime int64) ([]sqlc.FMRecord, error) {
	ret := _m.Called(ctx, userId, recordType, startTime, endTime)

	if len(ret) == 0 {
		panic("no return value specified for GetUserRecordsByTypeWithPeriod")
	}

	var r0 []sqlc.FMRecord
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string, int64, int64) ([]sqlc.FMRecord, error)); ok {
		return rf(ctx, userId, recordType, startTime, endTime)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, string, int64, int64) []sqlc.FMRecord); ok {
		r0 = rf(ctx, userId, recordType, startTime, endTime)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]sqlc.FMRecord)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, string, int64, int64) error); ok {
		r1 = rf(ctx, userId, recordType, startTime, endTime)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserRecordsFromDate provides a mock function with given fields: ctx, userId, date
func (_m *RecordRepository) GetUserRecordsFromDate(ctx context.Context, userId int64, date int64) ([]sqlc.FMRecord, error) {
	ret := _m.Called(ctx, userId, date)

	if len(ret) == 0 {
		panic("no return value specified for GetUserRecordsFromDate")
	}

	var r0 []sqlc.FMRecord
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) ([]sqlc.FMRecord, error)); ok {
		return rf(ctx, userId, date)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) []sqlc.FMRecord); ok {
		r0 = rf(ctx, userId, date)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]sqlc.FMRecord)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, int64) error); ok {
		r1 = rf(ctx, userId, date)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserRecordsToDate provides a mock function with given fields: ctx, userId, date
func (_m *RecordRepository) GetUserRecordsToDate(ctx context.Context, userId int64, date int64) ([]sqlc.FMRecord, error) {
	ret := _m.Called(ctx, userId, date)

	if len(ret) == 0 {
		panic("no return value specified for GetUserRecordsToDate")
	}

	var r0 []sqlc.FMRecord
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) ([]sqlc.FMRecord, error)); ok {
		return rf(ctx, userId, date)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) []sqlc.FMRecord); ok {
		r0 = rf(ctx, userId, date)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]sqlc.FMRecord)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, int64) error); ok {
		r1 = rf(ctx, userId, date)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserRecordsWithPeriod provides a mock function with given fields: ctx, userId, startTime, endTime
func (_m *RecordRepository) GetUserRecordsWithPeriod(ctx context.Context, userId int64, startTime int64, endTime int64) ([]sqlc.FMRecord, error) {
	ret := _m.Called(ctx, userId, startTime, endTime)

	if len(ret) == 0 {
		panic("no return value specified for GetUserRecordsWithPeriod")
	}

	var r0 []sqlc.FMRecord
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64, int64) ([]sqlc.FMRecord, error)); ok {
		return rf(ctx, userId, startTime, endTime)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64, int64) []sqlc.FMRecord); ok {
		r0 = rf(ctx, userId, startTime, endTime)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]sqlc.FMRecord)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, int64, int64) error); ok {
		r1 = rf(ctx, userId, startTime, endTime)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateRecord provides a mock function with given fields: ctx, id, amount, transactionDate, recordType, detail
func (_m *RecordRepository) UpdateRecord(ctx context.Context, id int64, amount float32, transactionDate int64, recordType string, detail string) error {
	ret := _m.Called(ctx, id, amount, transactionDate, recordType, detail)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRecord")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, float32, int64, string, string) error); ok {
		r0 = rf(ctx, id, amount, transactionDate, recordType, detail)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewRecordRepository creates a new instance of RecordRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRecordRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *RecordRepository {
	mock := &RecordRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
