// Code generated by mockery v2.52.3. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	sqlc "records/postgres/sqlc"
)

// RecordRepository is an autogenerated mock type for the RecordRepository type
type RecordRepository struct {
	mock.Mock
}

// CreateRecord provides a mock function with given fields: userId, amount, transactionDate, recordType, detail
func (_m *RecordRepository) CreateRecord(userId int64, amount float32, transactionDate int64, recordType string, detail string) (sqlc.FinanceManagerFMRecord, error) {
	ret := _m.Called(userId, amount, transactionDate, recordType, detail)

	if len(ret) == 0 {
		panic("no return value specified for CreateRecord")
	}

	var r0 sqlc.FinanceManagerFMRecord
	var r1 error
	if rf, ok := ret.Get(0).(func(int64, float32, int64, string, string) (sqlc.FinanceManagerFMRecord, error)); ok {
		return rf(userId, amount, transactionDate, recordType, detail)
	}
	if rf, ok := ret.Get(0).(func(int64, float32, int64, string, string) sqlc.FinanceManagerFMRecord); ok {
		r0 = rf(userId, amount, transactionDate, recordType, detail)
	} else {
		r0 = ret.Get(0).(sqlc.FinanceManagerFMRecord)
	}

	if rf, ok := ret.Get(1).(func(int64, float32, int64, string, string) error); ok {
		r1 = rf(userId, amount, transactionDate, recordType, detail)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteRecord provides a mock function with given fields: id
func (_m *RecordRepository) DeleteRecord(id int64) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteRecord")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int64) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetRecord provides a mock function with given fields: id
func (_m *RecordRepository) GetRecord(id int64) (*sqlc.FinanceManagerFMRecord, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetRecord")
	}

	var r0 *sqlc.FinanceManagerFMRecord
	var r1 error
	if rf, ok := ret.Get(0).(func(int64) (*sqlc.FinanceManagerFMRecord, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int64) *sqlc.FinanceManagerFMRecord); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sqlc.FinanceManagerFMRecord)
		}
	}

	if rf, ok := ret.Get(1).(func(int64) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserRecords provides a mock function with given fields: userId
func (_m *RecordRepository) GetUserRecords(userId int64) ([]sqlc.FinanceManagerFMRecord, error) {
	ret := _m.Called(userId)

	if len(ret) == 0 {
		panic("no return value specified for GetUserRecords")
	}

	var r0 []sqlc.FinanceManagerFMRecord
	var r1 error
	if rf, ok := ret.Get(0).(func(int64) ([]sqlc.FinanceManagerFMRecord, error)); ok {
		return rf(userId)
	}
	if rf, ok := ret.Get(0).(func(int64) []sqlc.FinanceManagerFMRecord); ok {
		r0 = rf(userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]sqlc.FinanceManagerFMRecord)
		}
	}

	if rf, ok := ret.Get(1).(func(int64) error); ok {
		r1 = rf(userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserRecordsByType provides a mock function with given fields: userId, recordType
func (_m *RecordRepository) GetUserRecordsByType(userId int64, recordType string) ([]sqlc.FinanceManagerFMRecord, error) {
	ret := _m.Called(userId, recordType)

	if len(ret) == 0 {
		panic("no return value specified for GetUserRecordsByType")
	}

	var r0 []sqlc.FinanceManagerFMRecord
	var r1 error
	if rf, ok := ret.Get(0).(func(int64, string) ([]sqlc.FinanceManagerFMRecord, error)); ok {
		return rf(userId, recordType)
	}
	if rf, ok := ret.Get(0).(func(int64, string) []sqlc.FinanceManagerFMRecord); ok {
		r0 = rf(userId, recordType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]sqlc.FinanceManagerFMRecord)
		}
	}

	if rf, ok := ret.Get(1).(func(int64, string) error); ok {
		r1 = rf(userId, recordType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserRecordsByTypeFromDate provides a mock function with given fields: userId, recordType, date
func (_m *RecordRepository) GetUserRecordsByTypeFromDate(userId int64, recordType string, date int64) ([]sqlc.FinanceManagerFMRecord, error) {
	ret := _m.Called(userId, recordType, date)

	if len(ret) == 0 {
		panic("no return value specified for GetUserRecordsByTypeFromDate")
	}

	var r0 []sqlc.FinanceManagerFMRecord
	var r1 error
	if rf, ok := ret.Get(0).(func(int64, string, int64) ([]sqlc.FinanceManagerFMRecord, error)); ok {
		return rf(userId, recordType, date)
	}
	if rf, ok := ret.Get(0).(func(int64, string, int64) []sqlc.FinanceManagerFMRecord); ok {
		r0 = rf(userId, recordType, date)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]sqlc.FinanceManagerFMRecord)
		}
	}

	if rf, ok := ret.Get(1).(func(int64, string, int64) error); ok {
		r1 = rf(userId, recordType, date)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserRecordsByTypeToDate provides a mock function with given fields: userId, recordType, date
func (_m *RecordRepository) GetUserRecordsByTypeToDate(userId int64, recordType string, date int64) ([]sqlc.FinanceManagerFMRecord, error) {
	ret := _m.Called(userId, recordType, date)

	if len(ret) == 0 {
		panic("no return value specified for GetUserRecordsByTypeToDate")
	}

	var r0 []sqlc.FinanceManagerFMRecord
	var r1 error
	if rf, ok := ret.Get(0).(func(int64, string, int64) ([]sqlc.FinanceManagerFMRecord, error)); ok {
		return rf(userId, recordType, date)
	}
	if rf, ok := ret.Get(0).(func(int64, string, int64) []sqlc.FinanceManagerFMRecord); ok {
		r0 = rf(userId, recordType, date)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]sqlc.FinanceManagerFMRecord)
		}
	}

	if rf, ok := ret.Get(1).(func(int64, string, int64) error); ok {
		r1 = rf(userId, recordType, date)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserRecordsByTypeWithPeriod provides a mock function with given fields: userId, recordType, startTime, endTime
func (_m *RecordRepository) GetUserRecordsByTypeWithPeriod(userId int64, recordType string, startTime int64, endTime int64) ([]sqlc.FinanceManagerFMRecord, error) {
	ret := _m.Called(userId, recordType, startTime, endTime)

	if len(ret) == 0 {
		panic("no return value specified for GetUserRecordsByTypeWithPeriod")
	}

	var r0 []sqlc.FinanceManagerFMRecord
	var r1 error
	if rf, ok := ret.Get(0).(func(int64, string, int64, int64) ([]sqlc.FinanceManagerFMRecord, error)); ok {
		return rf(userId, recordType, startTime, endTime)
	}
	if rf, ok := ret.Get(0).(func(int64, string, int64, int64) []sqlc.FinanceManagerFMRecord); ok {
		r0 = rf(userId, recordType, startTime, endTime)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]sqlc.FinanceManagerFMRecord)
		}
	}

	if rf, ok := ret.Get(1).(func(int64, string, int64, int64) error); ok {
		r1 = rf(userId, recordType, startTime, endTime)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserRecordsFromDate provides a mock function with given fields: userId, date
func (_m *RecordRepository) GetUserRecordsFromDate(userId int64, date int64) ([]sqlc.FinanceManagerFMRecord, error) {
	ret := _m.Called(userId, date)

	if len(ret) == 0 {
		panic("no return value specified for GetUserRecordsFromDate")
	}

	var r0 []sqlc.FinanceManagerFMRecord
	var r1 error
	if rf, ok := ret.Get(0).(func(int64, int64) ([]sqlc.FinanceManagerFMRecord, error)); ok {
		return rf(userId, date)
	}
	if rf, ok := ret.Get(0).(func(int64, int64) []sqlc.FinanceManagerFMRecord); ok {
		r0 = rf(userId, date)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]sqlc.FinanceManagerFMRecord)
		}
	}

	if rf, ok := ret.Get(1).(func(int64, int64) error); ok {
		r1 = rf(userId, date)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserRecordsToDate provides a mock function with given fields: userId, date
func (_m *RecordRepository) GetUserRecordsToDate(userId int64, date int64) ([]sqlc.FinanceManagerFMRecord, error) {
	ret := _m.Called(userId, date)

	if len(ret) == 0 {
		panic("no return value specified for GetUserRecordsToDate")
	}

	var r0 []sqlc.FinanceManagerFMRecord
	var r1 error
	if rf, ok := ret.Get(0).(func(int64, int64) ([]sqlc.FinanceManagerFMRecord, error)); ok {
		return rf(userId, date)
	}
	if rf, ok := ret.Get(0).(func(int64, int64) []sqlc.FinanceManagerFMRecord); ok {
		r0 = rf(userId, date)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]sqlc.FinanceManagerFMRecord)
		}
	}

	if rf, ok := ret.Get(1).(func(int64, int64) error); ok {
		r1 = rf(userId, date)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserRecordsWithPeriod provides a mock function with given fields: userId, startTime, endTime
func (_m *RecordRepository) GetUserRecordsWithPeriod(userId int64, startTime int64, endTime int64) ([]sqlc.FinanceManagerFMRecord, error) {
	ret := _m.Called(userId, startTime, endTime)

	if len(ret) == 0 {
		panic("no return value specified for GetUserRecordsWithPeriod")
	}

	var r0 []sqlc.FinanceManagerFMRecord
	var r1 error
	if rf, ok := ret.Get(0).(func(int64, int64, int64) ([]sqlc.FinanceManagerFMRecord, error)); ok {
		return rf(userId, startTime, endTime)
	}
	if rf, ok := ret.Get(0).(func(int64, int64, int64) []sqlc.FinanceManagerFMRecord); ok {
		r0 = rf(userId, startTime, endTime)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]sqlc.FinanceManagerFMRecord)
		}
	}

	if rf, ok := ret.Get(1).(func(int64, int64, int64) error); ok {
		r1 = rf(userId, startTime, endTime)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateRecord provides a mock function with given fields: id, amount, transactionDate, recordType, detail
func (_m *RecordRepository) UpdateRecord(id int64, amount float32, transactionDate int64, recordType string, detail string) error {
	ret := _m.Called(id, amount, transactionDate, recordType, detail)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRecord")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int64, float32, int64, string, string) error); ok {
		r0 = rf(id, amount, transactionDate, recordType, detail)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewRecordRepository creates a new instance of RecordRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRecordRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *RecordRepository {
	mock := &RecordRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
