// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type FinanceManagerFMRecord struct {
	ID              int64              `json:"id"`
	UserID          int64              `json:"user_id"`
	Amount          float32            `json:"amount"`
	TransactionDate pgtype.Date        `json:"transaction_date"`
	RecordType      string             `json:"record_type"`
	Detail          string             `json:"detail"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}
