// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: query.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRecord = `-- name: CreateRecord :one

INSERT INTO "finance_manager"."FM_Record" (user_id, amount, transaction_date, record_type, detail)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, amount, transaction_date, record_type, detail, created_at, updated_at
`

type CreateRecordParams struct {
	UserID          int64       `json:"user_id"`
	Amount          float32     `json:"amount"`
	TransactionDate pgtype.Date `json:"transaction_date"`
	RecordType      string      `json:"record_type"`
	Detail          string      `json:"detail"`
}

// Table: Record
func (q *Queries) CreateRecord(ctx context.Context, arg CreateRecordParams) (FinanceManagerFMRecord, error) {
	row := q.db.QueryRow(ctx, createRecord,
		arg.UserID,
		arg.Amount,
		arg.TransactionDate,
		arg.RecordType,
		arg.Detail,
	)
	var i FinanceManagerFMRecord
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Amount,
		&i.TransactionDate,
		&i.RecordType,
		&i.Detail,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRecord = `-- name: DeleteRecord :exec
DELETE FROM "finance_manager"."FM_Record" WHERE id = $1
`

func (q *Queries) DeleteRecord(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteRecord, id)
	return err
}

const getRecord = `-- name: GetRecord :one
SELECT id, user_id, amount, transaction_date, record_type, detail, created_at, updated_at FROM "finance_manager"."FM_Record" WHERE id = $1
`

func (q *Queries) GetRecord(ctx context.Context, id int64) (FinanceManagerFMRecord, error) {
	row := q.db.QueryRow(ctx, getRecord, id)
	var i FinanceManagerFMRecord
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Amount,
		&i.TransactionDate,
		&i.RecordType,
		&i.Detail,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserRecords = `-- name: GetUserRecords :many
SELECT id, user_id, amount, transaction_date, record_type, detail, created_at, updated_at FROM "finance_manager"."FM_Record" WHERE user_id = $1
`

func (q *Queries) GetUserRecords(ctx context.Context, userID int64) ([]FinanceManagerFMRecord, error) {
	rows, err := q.db.Query(ctx, getUserRecords, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FinanceManagerFMRecord
	for rows.Next() {
		var i FinanceManagerFMRecord
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Amount,
			&i.TransactionDate,
			&i.RecordType,
			&i.Detail,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserRecordsByType = `-- name: GetUserRecordsByType :many
SELECT id, user_id, amount, transaction_date, record_type, detail, created_at, updated_at FROM "finance_manager"."FM_Record"
WHERE user_id = $1 AND record_type = $2
`

type GetUserRecordsByTypeParams struct {
	UserID     int64  `json:"user_id"`
	RecordType string `json:"record_type"`
}

func (q *Queries) GetUserRecordsByType(ctx context.Context, arg GetUserRecordsByTypeParams) ([]FinanceManagerFMRecord, error) {
	rows, err := q.db.Query(ctx, getUserRecordsByType, arg.UserID, arg.RecordType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FinanceManagerFMRecord
	for rows.Next() {
		var i FinanceManagerFMRecord
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Amount,
			&i.TransactionDate,
			&i.RecordType,
			&i.Detail,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserRecordsByTypeFromDate = `-- name: GetUserRecordsByTypeFromDate :many
SELECT id, user_id, amount, transaction_date, record_type, detail, created_at, updated_at FROM "finance_manager"."FM_Record"
WHERE user_id = $1 AND record_type = $2 AND transaction_date >= $3
`

type GetUserRecordsByTypeFromDateParams struct {
	UserID          int64       `json:"user_id"`
	RecordType      string      `json:"record_type"`
	TransactionDate pgtype.Date `json:"transaction_date"`
}

func (q *Queries) GetUserRecordsByTypeFromDate(ctx context.Context, arg GetUserRecordsByTypeFromDateParams) ([]FinanceManagerFMRecord, error) {
	rows, err := q.db.Query(ctx, getUserRecordsByTypeFromDate, arg.UserID, arg.RecordType, arg.TransactionDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FinanceManagerFMRecord
	for rows.Next() {
		var i FinanceManagerFMRecord
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Amount,
			&i.TransactionDate,
			&i.RecordType,
			&i.Detail,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserRecordsByTypeToDate = `-- name: GetUserRecordsByTypeToDate :many
SELECT id, user_id, amount, transaction_date, record_type, detail, created_at, updated_at FROM "finance_manager"."FM_Record"
WHERE user_id = $1 AND record_type = $2 AND transaction_date <= $3
`

type GetUserRecordsByTypeToDateParams struct {
	UserID          int64       `json:"user_id"`
	RecordType      string      `json:"record_type"`
	TransactionDate pgtype.Date `json:"transaction_date"`
}

func (q *Queries) GetUserRecordsByTypeToDate(ctx context.Context, arg GetUserRecordsByTypeToDateParams) ([]FinanceManagerFMRecord, error) {
	rows, err := q.db.Query(ctx, getUserRecordsByTypeToDate, arg.UserID, arg.RecordType, arg.TransactionDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FinanceManagerFMRecord
	for rows.Next() {
		var i FinanceManagerFMRecord
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Amount,
			&i.TransactionDate,
			&i.RecordType,
			&i.Detail,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserRecordsByTypeWithPeriod = `-- name: GetUserRecordsByTypeWithPeriod :many
SELECT id, user_id, amount, transaction_date, record_type, detail, created_at, updated_at FROM "finance_manager"."FM_Record"
WHERE user_id = $1 AND record_type = $2 AND transaction_date BETWEEN $3 AND $4
`

type GetUserRecordsByTypeWithPeriodParams struct {
	UserID            int64       `json:"user_id"`
	RecordType        string      `json:"record_type"`
	TransactionDate   pgtype.Date `json:"transaction_date"`
	TransactionDate_2 pgtype.Date `json:"transaction_date_2"`
}

func (q *Queries) GetUserRecordsByTypeWithPeriod(ctx context.Context, arg GetUserRecordsByTypeWithPeriodParams) ([]FinanceManagerFMRecord, error) {
	rows, err := q.db.Query(ctx, getUserRecordsByTypeWithPeriod,
		arg.UserID,
		arg.RecordType,
		arg.TransactionDate,
		arg.TransactionDate_2,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FinanceManagerFMRecord
	for rows.Next() {
		var i FinanceManagerFMRecord
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Amount,
			&i.TransactionDate,
			&i.RecordType,
			&i.Detail,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserRecordsFromDate = `-- name: GetUserRecordsFromDate :many
SELECT id, user_id, amount, transaction_date, record_type, detail, created_at, updated_at FROM "finance_manager"."FM_Record"
WHERE user_id = $1 AND transaction_date >= $2
`

type GetUserRecordsFromDateParams struct {
	UserID          int64       `json:"user_id"`
	TransactionDate pgtype.Date `json:"transaction_date"`
}

func (q *Queries) GetUserRecordsFromDate(ctx context.Context, arg GetUserRecordsFromDateParams) ([]FinanceManagerFMRecord, error) {
	rows, err := q.db.Query(ctx, getUserRecordsFromDate, arg.UserID, arg.TransactionDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FinanceManagerFMRecord
	for rows.Next() {
		var i FinanceManagerFMRecord
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Amount,
			&i.TransactionDate,
			&i.RecordType,
			&i.Detail,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserRecordsToDate = `-- name: GetUserRecordsToDate :many
SELECT id, user_id, amount, transaction_date, record_type, detail, created_at, updated_at FROM "finance_manager"."FM_Record"
WHERE user_id = $1 AND transaction_date <= $2
`

type GetUserRecordsToDateParams struct {
	UserID          int64       `json:"user_id"`
	TransactionDate pgtype.Date `json:"transaction_date"`
}

func (q *Queries) GetUserRecordsToDate(ctx context.Context, arg GetUserRecordsToDateParams) ([]FinanceManagerFMRecord, error) {
	rows, err := q.db.Query(ctx, getUserRecordsToDate, arg.UserID, arg.TransactionDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FinanceManagerFMRecord
	for rows.Next() {
		var i FinanceManagerFMRecord
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Amount,
			&i.TransactionDate,
			&i.RecordType,
			&i.Detail,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserRecordsWithPeriod = `-- name: GetUserRecordsWithPeriod :many
SELECT id, user_id, amount, transaction_date, record_type, detail, created_at, updated_at FROM "finance_manager"."FM_Record"
WHERE user_id = $1 AND transaction_date BETWEEN $2 AND $3
`

type GetUserRecordsWithPeriodParams struct {
	UserID            int64       `json:"user_id"`
	TransactionDate   pgtype.Date `json:"transaction_date"`
	TransactionDate_2 pgtype.Date `json:"transaction_date_2"`
}

func (q *Queries) GetUserRecordsWithPeriod(ctx context.Context, arg GetUserRecordsWithPeriodParams) ([]FinanceManagerFMRecord, error) {
	rows, err := q.db.Query(ctx, getUserRecordsWithPeriod, arg.UserID, arg.TransactionDate, arg.TransactionDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FinanceManagerFMRecord
	for rows.Next() {
		var i FinanceManagerFMRecord
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Amount,
			&i.TransactionDate,
			&i.RecordType,
			&i.Detail,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRecord = `-- name: UpdateRecord :exec
UPDATE "finance_manager"."FM_Record" SET amount = $2, transaction_date = $3, record_type = $4, detail = $5, updated_time = NOW() WHERE id = $1
`

type UpdateRecordParams struct {
	ID              int64       `json:"id"`
	Amount          float32     `json:"amount"`
	TransactionDate pgtype.Date `json:"transaction_date"`
	RecordType      string      `json:"record_type"`
	Detail          string      `json:"detail"`
}

func (q *Queries) UpdateRecord(ctx context.Context, arg UpdateRecordParams) error {
	_, err := q.db.Exec(ctx, updateRecord,
		arg.ID,
		arg.Amount,
		arg.TransactionDate,
		arg.RecordType,
		arg.Detail,
	)
	return err
}
