// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: records_bank.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BankRecordService_GetBankRecord_FullMethodName                 = "/records_bank.BankRecordService/GetBankRecord"
	BankRecordService_GetUserBankRecordsWithFilters_FullMethodName = "/records_bank.BankRecordService/GetUserBankRecordsWithFilters"
)

// BankRecordServiceClient is the client API for BankRecordService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BankRecordServiceClient interface {
	GetBankRecord(ctx context.Context, in *GetBankRecordRequest, opts ...grpc.CallOption) (*BankRecordResponse, error)
	// /v1/bank_records/user?user_id&account_number&record_type&start_time&end_time
	GetUserBankRecordsWithFilters(ctx context.Context, in *GetUserBankRecordsWithFiltersRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[BankRecordResponse], error)
}

type bankRecordServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBankRecordServiceClient(cc grpc.ClientConnInterface) BankRecordServiceClient {
	return &bankRecordServiceClient{cc}
}

func (c *bankRecordServiceClient) GetBankRecord(ctx context.Context, in *GetBankRecordRequest, opts ...grpc.CallOption) (*BankRecordResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BankRecordResponse)
	err := c.cc.Invoke(ctx, BankRecordService_GetBankRecord_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankRecordServiceClient) GetUserBankRecordsWithFilters(ctx context.Context, in *GetUserBankRecordsWithFiltersRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[BankRecordResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &BankRecordService_ServiceDesc.Streams[0], BankRecordService_GetUserBankRecordsWithFilters_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetUserBankRecordsWithFiltersRequest, BankRecordResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BankRecordService_GetUserBankRecordsWithFiltersClient = grpc.ServerStreamingClient[BankRecordResponse]

// BankRecordServiceServer is the server API for BankRecordService service.
// All implementations must embed UnimplementedBankRecordServiceServer
// for forward compatibility.
type BankRecordServiceServer interface {
	GetBankRecord(context.Context, *GetBankRecordRequest) (*BankRecordResponse, error)
	// /v1/bank_records/user?user_id&account_number&record_type&start_time&end_time
	GetUserBankRecordsWithFilters(*GetUserBankRecordsWithFiltersRequest, grpc.ServerStreamingServer[BankRecordResponse]) error
	mustEmbedUnimplementedBankRecordServiceServer()
}

// UnimplementedBankRecordServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBankRecordServiceServer struct{}

func (UnimplementedBankRecordServiceServer) GetBankRecord(context.Context, *GetBankRecordRequest) (*BankRecordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBankRecord not implemented")
}
func (UnimplementedBankRecordServiceServer) GetUserBankRecordsWithFilters(*GetUserBankRecordsWithFiltersRequest, grpc.ServerStreamingServer[BankRecordResponse]) error {
	return status.Errorf(codes.Unimplemented, "method GetUserBankRecordsWithFilters not implemented")
}
func (UnimplementedBankRecordServiceServer) mustEmbedUnimplementedBankRecordServiceServer() {}
func (UnimplementedBankRecordServiceServer) testEmbeddedByValue()                           {}

// UnsafeBankRecordServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BankRecordServiceServer will
// result in compilation errors.
type UnsafeBankRecordServiceServer interface {
	mustEmbedUnimplementedBankRecordServiceServer()
}

func RegisterBankRecordServiceServer(s grpc.ServiceRegistrar, srv BankRecordServiceServer) {
	// If the following call pancis, it indicates UnimplementedBankRecordServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BankRecordService_ServiceDesc, srv)
}

func _BankRecordService_GetBankRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBankRecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankRecordServiceServer).GetBankRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BankRecordService_GetBankRecord_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankRecordServiceServer).GetBankRecord(ctx, req.(*GetBankRecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BankRecordService_GetUserBankRecordsWithFilters_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetUserBankRecordsWithFiltersRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BankRecordServiceServer).GetUserBankRecordsWithFilters(m, &grpc.GenericServerStream[GetUserBankRecordsWithFiltersRequest, BankRecordResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BankRecordService_GetUserBankRecordsWithFiltersServer = grpc.ServerStreamingServer[BankRecordResponse]

// BankRecordService_ServiceDesc is the grpc.ServiceDesc for BankRecordService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BankRecordService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "records_bank.BankRecordService",
	HandlerType: (*BankRecordServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBankRecord",
			Handler:    _BankRecordService_GetBankRecord_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetUserBankRecordsWithFilters",
			Handler:       _BankRecordService_GetUserBankRecordsWithFilters_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "records_bank.proto",
}
