name: test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '1.24'
      - name: Download all module deps
        run: |
          for dir in $(find . -name go.mod -exec dirname {} \;); do
            echo ">> tidy $dir"
            (cd "$dir" && go mod tidy)
          done
      - name: run tests
        run: find . -name 'go.mod' -exec dirname {} \; | xargs -I{} bash -c 'cd "{}" && go test ./...'
      - name: install golangci-lint
        run: |
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

  linter:
    runs-on: ubuntu-latest
    steps:
      - name: run golangci-lint
        run: |
          for dir in $(find . -name go.mod -exec dirname {} \;); do
            echo ">> lint $dir"
            (cd "$dir" && golangci-lint run)
          done
