name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '1.24'
      - name: set up go modules
        run: go mod tidy
      - name: run tests
        run: find . -name 'go.mod' -exec dirname {} \; | xargs -I{} bash -c 'cd "{}" && go test ./...'
